name: 'euro_data_jobs'
version: '1.0.0'
config-version: 2

profile: 'euro_data_jobs'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  euro_data_jobs:
    staging:
      +materialized: view
